import os
import re
import base64
import json
import uuid
import asyncio
import time
from pathlib import Path
from typing import List, Optional, Dict, Any
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, FileResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from openai import OpenAI
import chromadb
from langchain_core.messages import HumanMessage, AIMessage

# Background Tasks
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from apscheduler.schedulers.background import BackgroundScheduler
from github import Github

# Import from our engine
from create_embeddings import process_single_file, process_single_repo, DATA_DIR, GITHUB_USERNAME, GITHUB_TOKEN

# ================= CONFIG =================
load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
CHROMA_DIR = Path("chroma_db")
PROMPT_FILE = Path("prompt/prompt.txt")

if not OPENAI_API_KEY:
    print("⚠️ Missing OPENAI_API_KEY - AI chat features will be limited")

openai_client = OpenAI(api_key=OPENAI_API_KEY or "missing_key")
chroma_client = chromadb.PersistentClient(path=str(CHROMA_DIR))

# Collections (loaded on startup, but also accessed dynamically)
cv_collection = None
github_collection = None

def load_system_prompt():
    if PROMPT_FILE.exists():
        with open(PROMPT_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return "You are a helpful assistant for Saud Ahmad's portfolio."

SYSTEM_PROMPT = load_system_prompt()


# ================= PROJECT TOOL-CALLING =================
# Source of truth for every project the AI assistant can talk about is
# frontend/src/data/caseStudies.js — the same data the actual Projects
# pages render. `scripts/export_projects.mjs` exports it to this JSON file
# (index + full per-project pointers). Re-run that script whenever a
# project is added/edited on the site; this file is re-read on every chat
# request (same hot-reload pattern as the system prompt), so a fresh
# export takes effect immediately with no server restart.
PROJECTS_DATA_FILE = Path("data") / "projects.json"


def load_projects_data() -> Dict[str, Any]:
    """Load the exported project index + pointers. Never raises — a missing
    or malformed file just means the assistant temporarily has no project
    detail to pull from, not a broken chat."""
    if not PROJECTS_DATA_FILE.exists():
        print(f"⚠️ {PROJECTS_DATA_FILE} not found — run scripts/export_projects.mjs")
        return {"index": [], "pointers": {}}
    try:
        with open(PROJECTS_DATA_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        return {"index": data.get("index", []), "pointers": data.get("pointers", {})}
    except Exception as e:
        print(f"⚠️ Failed to load {PROJECTS_DATA_FILE}: {e}")
        return {"index": [], "pointers": {}}


def format_project_index(index: List[Dict[str, Any]]) -> str:
    """Render the compact project index injected into every system prompt so
    the model always knows what projects exist and their exact slugs, even
    before it decides to call get_project_details for full detail."""
    if not index:
        return "PROJECT INDEX: (none currently loaded)"
    lines = ["PROJECT INDEX (slug — title (category): tagline):"]
    for item in index:
        lines.append(
            f"- {item.get('slug')} — {item.get('title')} ({item.get('categoryLabel')}): {item.get('tagline')}"
        )
    return "\n".join(lines)


def get_project_details(slug: str) -> str:
    """Tool implementation: returns one project's full write-up by slug."""
    data = load_projects_data()
    pointer = data["pointers"].get(slug)
    if pointer:
        return pointer
    available = ", ".join(data["pointers"].keys()) or "(none loaded)"
    return f"No project found with slug '{slug}'. Available slugs: {available}"


# ================= CV =================
# Plain-text extraction of the exact PDF visitors download from /cv,
# regenerated by scripts/extract_cv_text.sh whenever the PDF is replaced.
# Read fresh on each call (same hot-reload pattern as the system prompt) so
# an updated CV takes effect without a restart.
CV_FILE = Path("data") / "cv.txt"


def get_cv_text() -> str:
    """Tool implementation: the full CV, verbatim."""
    if not CV_FILE.exists():
        return (
            "CV text is not available on the server (data/cv.txt missing — run "
            "scripts/extract_cv_text.sh). Answer from the background section of "
            "your prompt instead, and don't invent CV details."
        )
    try:
        with open(CV_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    except Exception as e:
        print(f"⚠️ Failed to read {CV_FILE}: {e}")
        return "CV text could not be read right now."


# ================= SITE MAP =================
# What lives where on the portfolio, so the assistant can point someone at the
# right page instead of vaguely saying "it's on the site somewhere". Kept in
# one place here rather than scattered through the prompt so it stays in sync
# with the actual routes in frontend/src/App.jsx.
SITE_MAP = """
PORTFOLIO SITE MAP (saudassist.up.railway.app) — where things actually live:

- /                Home. Intro, photo, quick links, and this chat assistant.
- /projects        Every project, all categories together.
- /skills          Full technical skills breakdown.
- /contact         Contact details and form.
- /cv              The CV, viewable in the browser and downloadable as a PDF.

Project categories (each is its own page at /<category>):
- /production      Production Systems — real client deployments.
- /ml              Machine Learning case studies.
- /dl              Deep Learning case studies.
- /rag             RAG & Retrieval studies.
- /agentic         Agentic AI.
- /vlm             Vision-Language & Multimodal.
- /finetuning      Fine-Tuning & PEFT.
- /robotics        Robotics & IoT.
- /tools           Tools & Utilities.

An individual project sits at /<category>/<slug>, e.g.
/rag/comparative-rag-techniques. The slugs are in the PROJECT INDEX below.

Every project page has the full write-up, real numbers, and where one exists,
a live demo you can actually run in the browser plus a link to the notebook.

When someone asks where to find something, give them the actual path, spoken
naturally — "it's on the projects page, under RAG" rather than reading out a
URL character by character.
""".strip()


PROJECT_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_cv",
            "description": (
                "Get the full text of Saud's actual CV — the same document visitors "
                "download from the portfolio. Call this for any question about his "
                "employment history, current or past job, employer names, job titles, "
                "dates, education, certifications, or what his CV says. Also call it "
                "when someone references the CV directly ('your CV says...'). This is "
                "the authoritative source for career facts."
            ),
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_project_details",
            "description": (
                "Get the complete write-up for one specific project — full narrative, "
                "tech stack, real metrics, and skills demonstrated. Call this with the "
                "project's exact slug from the PROJECT INDEX whenever the user asks about "
                "a specific project by name, or asks something a specific project would "
                "answer better than a generic summary."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "slug": {
                        "type": "string",
                        "description": "The project's exact slug from the PROJECT INDEX, e.g. 'coter-global-recruitment-agent'",
                    }
                },
                "required": ["slug"],
            },
        },
    }
]


def _execute_tool_call(name: str, arguments_json: str) -> str:
    """Dispatch a single tool call by name. Arguments arrive as a raw JSON
    string from the OpenAI API (streaming or not) — parsed defensively since
    a partially-formed or malformed call should never crash the chat."""
    try:
        args = json.loads(arguments_json) if arguments_json else {}
    except json.JSONDecodeError:
        args = {}

    if name == "get_project_details":
        return get_project_details(args.get("slug", ""))
    if name == "get_cv":
        return get_cv_text()
    return f"Unknown tool: {name}"


def run_chat_completion(messages: List[dict], max_tool_rounds: int = 3, max_tokens: int = 1000) -> str:
    """Non-streaming tool-calling loop used by /chat: ask the model, and if
    it wants a project's details, fetch them and ask again, up to a few
    rounds, until it produces a final text answer. `max_tokens` is lowered
    for spoken replies, where a long answer is a worse answer."""
    working_messages = list(messages)
    for _ in range(max_tool_rounds):
        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=working_messages,
            tools=PROJECT_TOOLS,
            tool_choice="auto",
            temperature=0.7,
            max_tokens=max_tokens,
        )
        choice = response.choices[0].message

        if choice.tool_calls:
            working_messages.append({
                "role": "assistant",
                "content": choice.content or "",
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {"name": tc.function.name, "arguments": tc.function.arguments},
                    }
                    for tc in choice.tool_calls
                ],
            })
            for tc in choice.tool_calls:
                result = _execute_tool_call(tc.function.name, tc.function.arguments)
                working_messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "content": result,
                })
            continue  # let the model use the tool result

        return choice.content or ""

    return (
        "I looked into a few things but couldn't quite pull it together — "
        "could you rephrase, or ask about one project at a time?"
    )


def stream_chat_completion(messages: List[dict], max_tool_rounds: int = 3, max_tokens: int = 1000):
    """Streaming counterpart of run_chat_completion, yielding {'type': 'content',
    'content': str} chunks for /chat/stream to forward as SSE events. Content
    deltas are forwarded live as they arrive; if a round turns out to be a
    tool call instead (the normal case — OpenAI's function-calling rounds
    carry no real content), nothing meaningful gets shown early, the tool
    is executed, and the loop asks the model again for the real answer."""
    working_messages = list(messages)
    for round_num in range(max_tool_rounds):
        stream = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=working_messages,
            tools=PROJECT_TOOLS,
            tool_choice="auto",
            temperature=0.7,
            max_tokens=max_tokens,
            stream=True,
        )

        tool_call_chunks: Dict[int, Dict[str, str]] = {}
        saw_tool_call = False

        for chunk in stream:
            delta = chunk.choices[0].delta

            if delta.tool_calls:
                saw_tool_call = True
                for tc_delta in delta.tool_calls:
                    slot = tool_call_chunks.setdefault(tc_delta.index, {"id": "", "name": "", "arguments": ""})
                    if tc_delta.id:
                        slot["id"] = tc_delta.id
                    if tc_delta.function:
                        if tc_delta.function.name:
                            slot["name"] += tc_delta.function.name
                        if tc_delta.function.arguments:
                            slot["arguments"] += tc_delta.function.arguments

            if delta.content and not saw_tool_call:
                yield {"type": "content", "content": delta.content}

        if saw_tool_call:
            tool_calls_sorted = [tool_call_chunks[i] for i in sorted(tool_call_chunks.keys())]
            working_messages.append({
                "role": "assistant",
                "content": "",
                "tool_calls": [
                    {
                        "id": tc["id"],
                        "type": "function",
                        "function": {"name": tc["name"], "arguments": tc["arguments"]},
                    }
                    for tc in tool_calls_sorted
                ],
            })
            for tc in tool_calls_sorted:
                result = _execute_tool_call(tc["name"], tc["arguments"])
                working_messages.append({
                    "role": "tool",
                    "tool_call_id": tc["id"],
                    "content": result,
                })
            continue  # next round: model answers using the tool result

        return  # finished a normal content round — done

    yield {
        "type": "content",
        "content": "I looked into a few things but couldn't quite pull it together — could you rephrase, or ask about one project at a time?",
    }

# ================= BACKGROUND SERVICES =================
class DataHandler(FileSystemEventHandler):
    """Watch for file changes in data directory"""
    def on_modified(self, event):
        if not event.is_directory and Path(event.src_path).suffix in [".txt", ".md", ".pdf", ".docx", ".doc"]:
            print(f"👀 File modified: {event.src_path}")
            process_single_file(Path(event.src_path))

    def on_created(self, event):
        if not event.is_directory and Path(event.src_path).suffix in [".txt", ".md", ".pdf", ".docx", ".doc"]:
            print(f"👀 File created: {event.src_path}")
            process_single_file(Path(event.src_path))

# ================= PROJECTS CACHE =================
# { "data": [...], "fetched_at": float }
_projects_cache: Dict[str, Any] = {}
PROJECTS_CACHE_TTL = 3600  # 1 hour

# Disk persistence: survives restarts. Manual sync writes here.
PROJECTS_FILE = Path("data") / "projects_cache.json"


def _bust_projects_cache():
    """Clear the in-memory projects cache so next request re-fetches from GitHub"""
    global _projects_cache
    _projects_cache = {}
    print("🗑️  Projects cache cleared (in-memory)")


def _load_projects_from_disk() -> Dict[str, Any]:
    """Load the persisted project cache from disk, if present."""
    if not PROJECTS_FILE.exists():
        return {}
    try:
        with open(PROJECTS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict) and "data" in data:
            print(f"💾 Loaded {len(data['data'])} projects from disk")
            return data
    except Exception as e:
        print(f"⚠️ Failed to load projects from disk: {e}")
    return {}


def _save_projects_to_disk(payload: Dict[str, Any]) -> None:
    """Persist the project cache to disk so it survives restarts."""
    try:
        PROJECTS_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(PROJECTS_FILE, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        print(f"💾 Saved {len(payload.get('data', []))} projects to {PROJECTS_FILE}")
    except Exception as e:
        print(f"⚠️ Failed to save projects to disk: {e}")


CATEGORY_PROMPT = """
You are a senior portfolio curator for an AI engineer. Given a GitHub repo's
metadata, write a polished project card. Be precise. Be specific. No fluff.

Return ONLY a valid JSON object with these exact keys:

- "title": 2–5 words, Title Case, *describes the actual product*. NO generic
  words like "AI Project", "Cool App", "Awesome Tool", "ML Demo". Use a real
  product-style name. Examples: "Resume Screener Bot", "PDF Q&A Agent",
  "Crypto Sentiment Tracker", "GPT-4 Code Reviewer". If the repo already has
  a clear product name, keep it.

- "description": 1–2 sentences, max 200 chars. State *what it does* and *for
  whom*, not how it was built. Skip "this project", "this repo", "leverages",
  "utilizes". Start with a verb when possible. Example:
  "Screens resumes against a job description and ranks candidates by fit,
  with explainable scoring."

- "impact": one short line (≤80 chars) about the value. Real metrics if the
  README has them ("3,500+ CVs processed · 80% faster screening"). Otherwise
  state the concrete user-facing benefit ("Cuts manual review time").

- "tech": array of 3–6 specific technologies actually used (e.g. "FastAPI",
  "OpenAI", "ChromaDB", "React", "PyTorch"). Skip generic words like "AI",
  "Machine Learning", "Backend".

- "category": EXACTLY ONE of the following. Read the definitions and pick
  the single best match. Default to "Experiments" only if nothing else fits.

    * "Agentic AI" — autonomous agents, multi-step task execution, tool use,
      LangGraph/CrewAI/AutoGPT-style flows, planning + acting loops.
    * "LLM Apps & RAG" — chatbots, document Q&A, retrieval-augmented
      generation, semantic search, prompt-engineered LLM features. Not
      autonomous agents.
    * "Machine Learning" — classical ML, deep learning, computer vision,
      NLP modeling, training pipelines, predictive models. Not LLM wrappers.
    * "Data Engineering" — ETL, scrapers, data pipelines, embeddings
      generation, feature stores, dataset builders, batch jobs.
    * "Developer Tools" — CLI tools, libraries, SDKs, dev utilities,
      automation scripts intended for other engineers.
    * "Web Apps" — full-stack web applications, SaaS products, dashboards,
      portfolios, marketing sites. Not pure backends.
    * "Experiments" — learning exercises, demos, half-finished prototypes,
      tutorial follow-alongs, single-purpose scripts, rough notebooks.

- "icon": a single relevant emoji (kept for legacy data; the UI no longer
  renders it but include one anyway).

- "featured": true ONLY if the repo looks substantial — has a real README,
  meaningful description, multiple commits, and represents production-style
  work. False for experiments, tutorials, and one-off scripts.

Do NOT wrap in markdown. Output raw JSON only.
"""

# Bumped whenever the prompt or category list changes — forces re-enrichment
# of any cards saved under an older schema on next sync.
PROMPT_SCHEMA_VERSION = 2

# Allowed categories (matches the prompt). Used to validate LLM output.
ALLOWED_CATEGORIES = {
    "Agentic AI",
    "LLM Apps & RAG",
    "Machine Learning",
    "Data Engineering",
    "Developer Tools",
    "Web Apps",
    "Experiments",
}


def _enrich_repo_with_llm(repo) -> Optional[Dict]:
    """Call GPT-4o-mini to turn raw GitHub repo data into a polished project card."""
    if not OPENAI_API_KEY:
        return None
    try:
        # Build a compact context for the LLM
        readme_snippet = ""
        try:
            raw = repo.get_readme().decoded_content.decode("utf-8")
            readme_snippet = raw[:800]  # first 800 chars
        except:
            pass

        topics = ", ".join(repo.get_topics()) if repo.get_topics() else "none"
        user_prompt = (
            f"Repo name: {repo.name}\n"
            f"GitHub description: {repo.description or 'none'}\n"
            f"Primary language: {repo.language or 'unknown'}\n"
            f"Stars: {repo.stargazers_count}\n"
            f"Topics: {topics}\n"
            f"README snippet:\n{readme_snippet}"
        )

        resp = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": CATEGORY_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=400,
        )
        enriched = json.loads(resp.choices[0].message.content)
        return enriched
    except Exception as e:
        print(f"  ⚠️ LLM enrichment failed for {repo.name}: {e}")
        return None


# Legacy gradient/border keys kept for payload shape compatibility.
# The frontend now uses GenerativeArt seeded by repoName instead.
_GRADIENTS = {cat: ("border-primary-600", "bg-primary-800 text-white") for cat in ALLOWED_CATEGORIES}


def _project_from_enriched(enriched: Dict, repo, idx: int) -> Dict:
    """Combine an LLM-enriched dict with raw repo metadata into a card payload."""
    cat = enriched.get("category", "Experiments")
    if cat not in ALLOWED_CATEGORIES:
        cat = "Experiments"
    gradient, border = _GRADIENTS.get(cat, ("border-primary-600", "bg-primary-800 text-white"))
    return {
        "id": idx + 1,
        "title": enriched.get("title", repo.name),
        "description": enriched.get("description", ""),
        "impact": enriched.get("impact", ""),
        "tech": enriched.get("tech", []),
        "category": cat,
        "github": repo.html_url,
        "featured": enriched.get("featured", False),
        "gradient": gradient,
        "borderGradient": border,
        "icon": enriched.get("icon", "💻"),
        "stars": repo.stargazers_count,
        "updatedAt": repo.pushed_at.isoformat() if repo.pushed_at else None,
        "repoName": repo.name,
        "schemaVersion": PROMPT_SCHEMA_VERSION,
    }


def _build_projects_list(existing: Optional[List[Dict]] = None) -> List[Dict]:
    """
    Fetch all GitHub repos and enrich each one via LLM.

    If `existing` is provided, repos that haven't changed since last enrichment
    (matched by repoName + updatedAt) are reused as-is — only new or modified
    repos are passed to the LLM. This keeps OpenAI cost / latency near zero
    for routine syncs.
    """
    if not GITHUB_TOKEN:
        print("⚠️ No GITHUB_TOKEN — cannot build projects list")
        return existing or []

    g = Github(GITHUB_TOKEN)
    try:
        user = g.get_user(GITHUB_USERNAME) if GITHUB_USERNAME else g.get_user()
        repos = list(user.get_repos(type="owner", sort="updated"))
    except Exception as e:
        print(f"❌ Error fetching repos: {e}")
        return existing or []

    # Index existing enriched cards by repoName for O(1) lookup
    existing_by_name: Dict[str, Dict] = {}
    if existing:
        for p in existing:
            if p.get("repoName"):
                existing_by_name[p["repoName"]] = p

    projects: List[Dict] = []
    reused = 0
    enriched_new = 0
    for idx, repo in enumerate(repos):
        if repo.fork:
            continue

        pushed_at_iso = repo.pushed_at.isoformat() if repo.pushed_at else None
        prev = existing_by_name.get(repo.name)

        # Reuse only if (a) repo unchanged since last enrichment AND
        # (b) we enriched it under the current prompt schema.
        prev_schema = prev.get("schemaVersion") if prev else None
        if (
            prev
            and prev.get("updatedAt") == pushed_at_iso
            and prev_schema == PROMPT_SCHEMA_VERSION
        ):
            updated = dict(prev)
            updated["id"] = idx + 1
            updated["stars"] = repo.stargazers_count
            updated["github"] = repo.html_url
            projects.append(updated)
            reused += 1
            continue

        enriched = _enrich_repo_with_llm(repo)
        if not enriched:
            enriched = {
                "title": repo.name.replace("-", " ").replace("_", " ").title(),
                "description": repo.description or "No description available.",
                "impact": f"{repo.stargazers_count} ⭐ · {repo.language or 'Code'}",
                "tech": [repo.language] if repo.language else [],
                "category": "Experiments",
                "icon": "💻",
                "featured": repo.stargazers_count > 2,
            }
        projects.append(_project_from_enriched(enriched, repo, idx))
        enriched_new += 1

    print(f"🔄 Built projects: {reused} reused, {enriched_new} newly enriched")

    # Sort: featured first, then by stars desc
    projects.sort(key=lambda p: (not p["featured"], -p["stars"]))
    return projects


def poll_github():
    """Hourly job: refresh embeddings and incrementally rebuild projects list."""
    print("⏰ Polling GitHub for updates...")
    if not GITHUB_TOKEN:
        return
    g = Github(GITHUB_TOKEN)
    try:
        user = g.get_user(GITHUB_USERNAME) if GITHUB_USERNAME else g.get_user()
        for repo in user.get_repos():
            process_single_repo(repo.name)
        # Incrementally update projects (no LLM call unless something changed)
        global _projects_cache
        existing = _projects_cache.get("data") if isinstance(_projects_cache, dict) else None
        projects = _build_projects_list(existing)
        _projects_cache = {"data": projects, "fetched_at": time.time()}
        _save_projects_to_disk(_projects_cache)
    except Exception as e:
        print(f"❌ Error polling GitHub: {e}")

@asynccontextmanager
async def lifespan(app: FastAPI):
    # 1. Load Collections
    global cv_collection, github_collection
    try:
        cv_collection = chroma_client.get_collection("cv_collection")
        print("✅ Loaded cv_collection")
    except:
        print("⚠️ cv_collection not found")

    try:
        github_collection = chroma_client.get_collection("github_collection")
        print("✅ Loaded github_collection")
    except:
        print("⚠️ github_collection not found")

    # 2. Start File Watcher
    observer = Observer()
    event_handler = DataHandler()
    if DATA_DIR.exists():
        observer.schedule(event_handler, str(DATA_DIR), recursive=False)
        observer.start()
        print(f"👀 Watching {DATA_DIR} for changes...")
    
    # 2.5 Load persisted projects cache from disk (survives restarts)
    global _projects_cache
    _projects_cache = _load_projects_from_disk()

    # 3. Start GitHub Poller (every hour, incremental)
    scheduler = BackgroundScheduler()
    scheduler.add_job(poll_github, 'interval', minutes=60)
    scheduler.start()
    print("⏰ GitHub poller started (60 min interval)")
    
    yield
    
    # Shutdown
    observer.stop()
    observer.join()
    scheduler.shutdown()
    print("🛑 Background services stopped")

# ================= APP =================

app = FastAPI(title="AskSaud API", version="2.1.0", lifespan=lifespan)

# Add health check for Railway
@app.get("/health")
async def health():
    return {"status": "healthy"}

# Churn prediction demo (ML case study "Try it live") — same-origin, no
# separate deployment or CORS wiring needed.
from churn_model import router as churn_router
app.include_router(churn_router)

# Heart disease prediction demo — same pattern.
from heart_model import router as heart_router
app.include_router(heart_router)

# Credit card fraud detection demo — same pattern.
from fraud_model import router as fraud_router
app.include_router(fraud_router)

# House price prediction demo — same pattern.
from house_model import router as house_router
app.include_router(house_router)

# Sales forecasting demo — same pattern, but serves a precomputed forecast
# rather than scoring live user input (monthly forecasts aren't a per-row
# prediction the way the other four projects are).
from sales_model import router as sales_router
app.include_router(sales_router)

# Movie recommender demo — same pattern, item-similarity lookup instead of
# scoring a single row.
from movie_model import router as movie_router
app.include_router(movie_router)

# Sentiment classifier demo — PyTorch LSTM
try:
    from sentiment_model import router as sentiment_router
    app.include_router(sentiment_router)
except ImportError as e:
    print(f"⚠️ sentiment_model router skipped: {e}")

# Agentic AI demo — LangGraph deep-research agent
from agentic_chat_model import router as agentic_chat_router
app.include_router(agentic_chat_router)

# Network anomaly detection demo
try:
    from anomaly_model import router as anomaly_router
    app.include_router(anomaly_router)
except ImportError as e:
    print(f"⚠️ anomaly_model router skipped: {e}")

# CLIP-based multimodal search
try:
    from clip_search_model import router as clip_search_router
    app.include_router(clip_search_router)
except ImportError as e:
    print(f"⚠️ clip_search_model router skipped: {e}")

# Mini-LLaVA
try:
    from mini_llava_model import router as mini_llava_router
    app.include_router(mini_llava_router)
except ImportError as e:
    print(f"⚠️ mini_llava_model router skipped: {e}")

# Diffusion vs GAN
try:
    from diffusion_gan_model import router as diffusion_gan_router
    app.include_router(diffusion_gan_router)
except ImportError as e:
    print(f"⚠️ diffusion_gan_model router skipped: {e}")

try:
    from gpt2_lora_model import router as gpt2_lora_router
    app.include_router(gpt2_lora_router)
except ImportError as e:
    print(f"⚠️ gpt2_lora_model router skipped: {e}")

try:
    from rag_model import router as rag_router
    app.include_router(rag_router)
except ImportError as e:
    print(f"⚠️ rag_model router skipped: {e}")


# Private portal — password-gated, single-user job tracker/prep/notes area.
# Not linked in the site nav; see private_model.py for how access works.
from private_model import router as private_router
app.include_router(private_router)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class CachedStaticFiles(StaticFiles):
    async def get_response(self, path: str, scope):
        response = await super().get_response(path, scope)
        response.headers.setdefault(
            "Cache-Control",
            "public, max-age=31536000, immutable",
        )
        return response


# ================= HELPERS =================
def get_embedding(text: str) -> List[float]:
    response = openai_client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )
    return response.data[0].embedding


def search_collections(query: str, n_results: int = 5) -> str:
    # Embedding the query can fail (missing OPENAI_API_KEY on the deploy host,
    # rate limit, network blip). Don't let that crash the chat — degrade
    # gracefully to "no context" so the LLM can still reply generically.
    try:
        query_embedding = get_embedding(query)
    except Exception as e:
        print(f"⚠️ get_embedding failed: {type(e).__name__}: {e}")
        return "No context found."

    context_parts = []

    # Reload collections if needed (in case they were recreated by bg process)
    try:
        current_cv = chroma_client.get_collection("cv_collection")
        results = current_cv.query(query_embeddings=[query_embedding], n_results=n_results)
        if results and results['documents'] and results['documents'][0]:
            context_parts.append("=== CV & EXPERIENCE ===")
            context_parts.extend(results['documents'][0])
    except Exception as e:
        print(f"⚠️ cv_collection query failed: {type(e).__name__}: {e}")

    try:
        current_gh = chroma_client.get_collection("github_collection")
        results = current_gh.query(query_embeddings=[query_embedding], n_results=n_results)
        if results and results['documents'] and results['documents'][0]:
            context_parts.append("\n=== GITHUB PROJECTS ===")
            context_parts.extend(results['documents'][0])
    except Exception as e:
        print(f"⚠️ github_collection query failed: {type(e).__name__}: {e}")

    return "\n\n".join(context_parts) if context_parts else "No context found."


# ================= SESSION =================
sessions: Dict[str, List] = {}

def get_or_create_session(session_id: Optional[str] = None) -> str:
    if session_id and session_id in sessions:
        return session_id
    new_id = str(uuid.uuid4())
    sessions[new_id] = []
    return new_id


# ---- per-session message cap ----
# Every real turn is at least one paid API call (an LLM completion), and a
# voice turn is three (STT, LLM, TTS). This assistant has no auth and no
# other rate limiting, so without a cap a single visitor — or a bot — could
# run up real cost with no ceiling. The cap resets per browser session
# (a fresh session_id) rather than per IP, matching how sessions already
# work here; it isn't meant to survive someone deliberately clearing state,
# only to stop an ordinary spam loop from being expensive.
MAX_MESSAGES_PER_SESSION = int(os.getenv("MAX_MESSAGES_PER_SESSION", "15"))
SESSION_LIMIT_MESSAGE = (
    "That's the limit I've got set on this for now — email me directly and "
    "I'll pick it up from there: sauds6446@gmail.com"
)


def session_message_count(history: List) -> int:
    return sum(1 for m in history if isinstance(m, HumanMessage))


def session_limit_reached(history: List) -> bool:
    return session_message_count(history) >= MAX_MESSAGES_PER_SESSION


# Style overlay applied only to spoken turns. The text assistant is allowed
# to be thorough and use markdown; out loud, that same answer sounds like a
# brochure being read at you. This layer keeps the underlying knowledge and
# tools identical while changing only the delivery: short, plain, spoken.
VOICE_STYLE_PROMPT = """
YOU ARE SPEAKING OUT LOUD. Your reply is read by a text-to-speech voice, so
write it the way a calm, grounded person actually talks — not the way an
article is written.

NEVER READ A LIST ALOUD. This is the most important rule here. Spoken lists
turn into one long flat drone that nobody can follow. If the honest answer is
a list, say roughly how many there are, name two or three, and stop. Then ask
which one they want.

  Asked "tell me about his projects", DO NOT recite every project. Say
  something like: "He's got a fair few up there. A lot of it's machine
  learning and retrieval work. There's some robotics and computer vision too.
  Which of those sounds interesting?"

Length:
- Two or three sentences is normal. One is often better.
- Never go past about five sentences, no matter what was asked.
- Answer the one thing that was asked. Nothing extra. No "would you also like
  to know about...". If they want more, they'll ask.

Rhythm — this is what stops it sounding robotic:
- Short sentences. End them with a full stop.
- A long sentence strung together with commas becomes one breathless run when
  it's spoken. Break it into separate sentences instead.
- Vary the length. A short one after a longer one keeps it from droning.
- Break where a person would actually pause for breath.

Tone:
- You are still Saud, speaking in first person, exactly as everywhere else in
  this prompt. Speaking out loud changes your delivery, never your identity.
- Plain and warm. Relaxed, not peppy. Confident, not salesy. You're just a
  person answering a question about your own work, not performing.
- Use contractions: "I'm", "it's", "that's". Natural speech over correct
  written grammar.
- Never say "I'm an AI assistant". Never narrate what you're about to do.
- Don't end every single turn with a question. Sometimes just answer and
  stop — a real person doesn't say "what else would you like to know?" after
  every sentence. Vary how you leave space for the next question, and often
  leave none at all.

WHEN YOU CAN'T MAKE OUT WHAT THEY SAID:
Speech gets transcribed before it reaches you, and the transcription is
sometimes wrong — especially on names. If a message is garbled, nonsensical,
or a single word you don't recognise, do NOT treat it as an off-topic question
and do NOT give the redirect line. Just say you didn't catch that and ask them
to say it again. Something like "Sorry, I didn't catch that — say it again?"

If a message is mostly clear but contains one odd-sounding name, assume it's a
mangled version of something you actually know rather than an unfamiliar
company. "Cotro Globe", "Kauter Global" and "Gator Global" are all COTER
Global. "Overlaps" is Oval Labs. Answer the question they meant to ask, and
it's fine to gently confirm the name as you do.

Never write:
- Any markdown. No asterisks, headers, bullets, numbered lists, links, code
  blocks. It all gets read out as literal noise.
- Emoji, arrows, or special symbols.
- URLs or file paths spelled out. Say "it's on the projects page" instead.
- A run of numbers. Pick the one figure that matters and say only that.

If the question is vague, ask one short question back rather than guessing at
a long answer.
""".strip()


def build_messages(history: List, voice: bool = False) -> List[dict]:
    current_system_prompt = load_system_prompt()
    project_index_text = format_project_index(load_projects_data()["index"])

    # The model otherwise has zero knowledge that a cap exists at all, so if
    # asked "how many questions do I have left?" it just guesses — usually
    # "unlimited" — which is exactly the kind of invented answer the rest of
    # this prompt tells it never to give. Telling it the real number lets it
    # answer honestly instead. `history` already includes this turn's own
    # HumanMessage by the time build_messages runs (every call site appends
    # before calling this), so the count below already reflects "after this
    # message" correctly.
    remaining = max(0, MAX_MESSAGES_PER_SESSION - session_message_count(history))
    session_limit_text = (
        f"SESSION LIMIT (factual, not for you to bring up unprompted): this chat is "
        f"capped at {MAX_MESSAGES_PER_SESSION} messages per browser session to keep "
        f"API costs bounded. {remaining} message(s) remain after this one. If asked "
        f"how many questions/messages are left, or whether there's a limit at all, "
        f"answer with this exact number honestly — never say it's unlimited or that "
        f"you don't know. Once the cap is reached, the app automatically shows a "
        f"message pointing to sauds6446@gmail.com; you don't need to mention that "
        f"yourself unless asked."
    )

    full_system = (
        f"{current_system_prompt}\n\n---\n\n{session_limit_text}\n\n---\n\n{SITE_MAP}\n\n---\n\n{project_index_text}"
    )
    if voice:
        full_system = f"{full_system}\n\n---\n\n{VOICE_STYLE_PROMPT}"
    messages = [{"role": "system", "content": full_system}]
    for msg in history:
        if isinstance(msg, HumanMessage):
            messages.append({"role": "user", "content": msg.content})
        elif isinstance(msg, AIMessage):
            messages.append({"role": "assistant", "content": msg.content})
    return messages


# ================= MODELS =================
class ChatRequest(BaseModel):
    message: str
    session_id: Optional[str] = None

class ChatResponse(BaseModel):
    response: str
    session_id: str

class HealthResponse(BaseModel):
    status: str
    cv_collection: bool
    github_collection: bool
    system_prompt_loaded: bool
    active_sessions: int


# ================= ENDPOINTS =================
@app.get("/")
async def root():
    dist_index = Path("frontend/dist/index.html")
    if dist_index.exists():
        return FileResponse(
            dist_index,
            headers={"Cache-Control": "no-cache"},
        )
    return {"message": "AskSaud API", "health": "/health"}


@app.get("/api/diag")
async def diagnostic():
    """
    Returns what the *running container* sees for critical env vars.
    Never returns the actual key — just length and first/last 4 chars so you
    can confirm the value matches what's in your Railway dashboard.
    """
    def fingerprint(key_name: str):
        v = os.getenv(key_name)
        if v is None:
            return {"present": False, "length": 0, "preview": None}
        v = v.strip()
        if not v:
            return {"present": False, "length": 0, "preview": "(empty string)"}
        preview = v[:4] + "..." + v[-4:] if len(v) >= 8 else "(too short)"
        return {"present": True, "length": len(v), "preview": preview}

    return {
        "OPENAI_API_KEY": fingerprint("OPENAI_API_KEY"),
        "GITHUB_TOKEN": fingerprint("GITHUB_TOKEN"),
        "GITHUB_USERNAME": {
            "present": bool(os.getenv("GITHUB_USERNAME")),
            "value": os.getenv("GITHUB_USERNAME"),
        },
        "module_OPENAI_API_KEY_loaded": bool(OPENAI_API_KEY),
    }


@app.get("/health", response_model=HealthResponse)
async def health():
    cv_ok = False
    gh_ok = False
    try:
        chroma_client.get_collection("cv_collection")
        cv_ok = True
        chroma_client.get_collection("github_collection")
        gh_ok = True
    except:
        pass

    return HealthResponse(
        status="healthy",
        cv_collection=cv_ok,
        github_collection=gh_ok,
        system_prompt_loaded=len(SYSTEM_PROMPT) > 0,
        active_sessions=len(sessions)
    )


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        session_id = get_or_create_session(request.session_id)
        history = sessions[session_id]

        # Checked against history BEFORE this message is added or any API
        # call is made — a session that's already at the cap costs nothing
        # more, not even a wasted LLM call.
        if session_limit_reached(history):
            return ChatResponse(response=SESSION_LIMIT_MESSAGE, session_id=session_id)

        history.append(HumanMessage(content=request.message))

        messages = build_messages(history)
        ai_response = run_chat_completion(messages)

        history.append(AIMessage(content=ai_response))
        sessions[session_id] = history

        return ChatResponse(response=ai_response, session_id=session_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    # Build everything we can BEFORE returning the StreamingResponse, but
    # never raise — any failure here is sent as an SSE 'error' event so the
    # frontend can surface it instead of getting an opaque HTTP 500.
    setup_error = None
    session_id = None
    messages = None
    history = None
    limit_hit = False
    try:
        session_id = get_or_create_session(request.session_id)
        history = sessions[session_id]
        if session_limit_reached(history):
            limit_hit = True
        else:
            history.append(HumanMessage(content=request.message))
            messages = build_messages(history)
    except Exception as e:
        import traceback
        traceback.print_exc()
        setup_error = f"{type(e).__name__}: {e}"
        print(f"❌ chat_stream setup failed: {setup_error}")

    def generate():
        if setup_error:
            yield f"data: {json.dumps({'type': 'error', 'error': setup_error})}\n\n"
            return

        if limit_hit:
            # No OpenAI call at all — a capped session costs nothing further.
            yield f"data: {json.dumps({'type': 'session', 'session_id': session_id})}\n\n"
            yield f"data: {json.dumps({'type': 'content', 'content': SESSION_LIMIT_MESSAGE})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"
            return

        full_response = ""
        try:
            yield f"data: {json.dumps({'type': 'session', 'session_id': session_id})}\n\n"

            if not OPENAI_API_KEY:
                yield f"data: {json.dumps({'type': 'error', 'error': 'OPENAI_API_KEY is not set on the server'})}\n\n"
                return

            for event in stream_chat_completion(messages):
                if event["type"] == "content" and event["content"]:
                    full_response += event["content"]
                    yield f"data: {json.dumps(event)}\n\n"

            history.append(AIMessage(content=full_response))
            sessions[session_id] = history
            yield f"data: {json.dumps({'type': 'done'})}\n\n"

        except Exception as e:
            import traceback
            traceback.print_exc()
            err = f"{type(e).__name__}: {e}"
            print(f"❌ chat_stream generation failed: {err}")
            yield f"data: {json.dumps({'type': 'error', 'error': err})}\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive", "X-Accel-Buffering": "no"}
    )


@app.delete("/session/{session_id}")
async def clear_session(session_id: str):
    if session_id in sessions:
        sessions[session_id] = []
    return {"message": "Session cleared"}


# ================= VOICE CHAT =================
# "onyx" reads calmer and lower than the default "alloy", which fits the
# grounded tone the voice prompt asks for.
VOICE_TTS_VOICE = os.getenv("VOICE_TTS_VOICE", "onyx")

# tts-1 has one flat delivery and no way to steer it, which is exactly the
# "same tone all the way through" problem. gpt-4o-mini-tts takes a free-text
# `instructions` field describing how to perform the line, so pacing and
# emphasis can actually be directed. If the model isn't available on this
# account we fall back to tts-1 rather than failing the turn.
VOICE_TTS_MODEL = os.getenv("VOICE_TTS_MODEL", "gpt-4o-mini-tts")
VOICE_TTS_FALLBACK_MODEL = "tts-1"

# whisper-1 is the older, slower transcription endpoint. gpt-4o-mini-transcribe
# is the faster one for short clips like these, which is most of what a voice
# turn sends. Overridable in case an account doesn't have it.
VOICE_STT_MODEL = os.getenv("VOICE_STT_MODEL", "gpt-4o-mini-transcribe")

VOICE_TTS_INSTRUCTIONS = (
    "Speak like a calm, friendly person having a normal conversation, not like "
    "someone reading a document aloud. Take a real breath at every full stop and "
    "a longer one at every line break. Let your pitch fall at the end of a "
    "sentence instead of running straight into the next one. Vary the pace: slow "
    "down slightly on the important word in a sentence, and move a little quicker "
    "through the small connecting words. Keep the overall energy relaxed and warm, "
    "never bright or announcer-like, and never flat or monotone."
)


def _strip_markdown_for_speech(text: str) -> str:
    """Belt-and-braces cleanup before TTS. The voice prompt already asks the
    model not to emit markdown, but if any slips through, these characters get
    read out as literal noise ("star star", "hash"), which instantly breaks
    the illusion of a person talking. Cheap to run, so we always run it."""
    import re

    cleaned = text
    cleaned = re.sub(r"```.*?```", " ", cleaned, flags=re.DOTALL)   # code fences
    cleaned = re.sub(r"`([^`]*)`", r"\1", cleaned)                  # inline code
    cleaned = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", cleaned)    # links/images
    cleaned = re.sub(r"^\s{0,3}#{1,6}\s*", "", cleaned, flags=re.MULTILINE)  # headers
    cleaned = re.sub(r"^\s*[-*+•▸◈]\s+", "", cleaned, flags=re.MULTILINE)    # bullets
    cleaned = re.sub(r"^\s*\d+[.)]\s+", "", cleaned, flags=re.MULTILINE)     # numbered
    cleaned = re.sub(r"(\*\*|__|\*|_)", "", cleaned)                # emphasis
    cleaned = re.sub(r"^\s*>\s?", "", cleaned, flags=re.MULTILINE)  # quotes
    cleaned = re.sub(r"[ \t]+", " ", cleaned)
    cleaned = re.sub(r"\n{2,}", "\n", cleaned)
    return cleaned.strip()


def _shape_for_speech(text: str) -> str:
    """Give the TTS engine something to breathe against.

    Every TTS model paces off punctuation and line breaks. A reply that comes
    back as one dense paragraph therefore gets read as one dense paragraph —
    which is the "it just talks in a single flow" problem. Putting each
    sentence on its own line converts the model's sentence boundaries into
    actual audible pauses, and splitting on semicolons/dashes breaks up the
    long comma-chains that otherwise get read without stopping."""
    import re

    text = _strip_markdown_for_speech(text)
    # Semicolons and dashes are written punctuation; spoken, they're just
    # full stops. Converting them creates a real pause instead of a glide.
    text = re.sub(r"\s*[;—–]\s*", ". ", text)
    text = re.sub(r"\s*:\s*", ". ", text)
    # Those replacements leave a lowercase word after the new full stop, which
    # would stop the sentence splitter below from seeing a boundary there.
    text = re.sub(r"([.!?]\s+)([a-z])", lambda m: m.group(1) + m.group(2).upper(), text)
    # One sentence per line. The uppercase lookahead keeps decimals and common
    # abbreviations ("3.5", "e.g.") from being split into odd little gaps.
    text = re.sub(r"(?<=[.!?])\s+(?=[A-Z])", "\n", text)
    lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
    return "\n".join(lines)


# Proper nouns the transcriber has no way to guess phonetically. Without this,
# "COTER Global" came back as "Cotro Globe", "Kauter Global" and "Gator
# Global" in a single conversation, and "Oval Labs" became "overlaps" — which
# then made the assistant think it was being asked about unrelated companies
# and refuse to answer. The API takes this as a vocabulary hint.
STT_VOCABULARY = (
    "This is a conversation with Saud Ahmad, an AI engineer. Expect these names: "
    "Saud Ahmad, COTER Global, Oval Labs, Nebula, Centauri, ZYP Technologies, "
    "TrueSight, AgroBot, Access Vision, HSE Performance Tracker, SmartNest, "
    "GIK Institute, Swat, Pakistan. Technical terms: RAG, retrieval augmented "
    "generation, LLM, LoRA, QLoRA, fine-tuning, embeddings, FAISS, LangChain, "
    "LangGraph, PyTorch, YOLOv8, CLIP, diffusion, GAN, agentic AI, FastAPI, React."
)


# Whisper-family models are trained to continue the `prompt` text, not just be
# biased by it. When a clip contains no intelligible speech (silence, room
# noise, a stray tap, a mic that opened and closed), the model has nothing to
# transcribe and its most likely continuation is the prompt itself — so it
# returns STT_VOCABULARY back verbatim, or a chunk of it. Without this guard
# that echo becomes the "transcript": it renders as the visitor's own caption
# in the UI and gets appended to history as a real user message, which is why
# the assistant then starts answering a prompt dump instead of a question.
#
# Same clip conditions also produce the well-known fixed hallucinations below
# (artifacts of the model's training data — subtitle corpora full of these).
_STT_HALLUCINATIONS = {
    "thank you", "thanks for watching", "thanks for watching!",
    "thank you for watching", "thank you very much", "you", "bye",
    "please subscribe", "subscribe to my channel", "okay", "ok",
    ".", "..", "...", "!", "?",
}


def _normalize_for_compare(text: str) -> str:
    """Lowercase, strip punctuation, collapse whitespace — so an echo that
    differs only in casing or trailing punctuation still matches."""
    return " ".join(re.sub(r"[^\w\s]", " ", text.lower()).split())


_STT_VOCAB_NORMALIZED = _normalize_for_compare(STT_VOCABULARY)
_STT_VOCAB_WORDS = set(_STT_VOCAB_NORMALIZED.split())


def _is_prompt_echo_or_noise(text: str) -> bool:
    """True when the transcript isn't real speech and must be discarded.

    Deliberately conservative: a real question from a visitor will naturally
    contain words that AREN'T in the vocabulary prompt ("what", "how", "tell
    me about"), so requiring a very high overlap ratio means a genuine
    question that happens to mention COTER Global or RAG is never dropped.
    """
    normalized = _normalize_for_compare(text)
    if not normalized:
        return True

    if normalized in _STT_HALLUCINATIONS:
        return True

    words = normalized.split()

    # Direct echo: the model returned the prompt, or a contiguous slice of it.
    # Gated on length because this is a substring test, and short utterances
    # produce false positives against a long prompt — "hi" is a substring of
    # "t-hi-s", so an unguarded check would silently swallow a real greeting.
    # A genuine echo is never this short; short noise is covered above.
    if len(words) >= 6 and (
        normalized in _STT_VOCAB_NORMALIZED or _STT_VOCAB_NORMALIZED in normalized
    ):
        return True

    # Partial/reordered echo. Only applied to long transcripts — a short reply
    # like "RAG and LoRA?" is legitimately ~100% vocabulary words, so scoring
    # it this way would wrongly discard it. Real spoken questions of this
    # length always carry filler and question words from outside the prompt.
    if len(words) >= 12:
        overlap = sum(1 for w in words if w in _STT_VOCAB_WORDS) / len(words)
        if overlap >= 0.85:
            return True

    return False


def _transcribe(filename: str, audio_bytes: bytes, content_type: str) -> str:
    """STT with the same graceful downgrade as TTS — a slower transcription is
    much better than a dead turn if the faster model isn't on this account.

    Returns "" for anything that isn't real speech, so every caller's existing
    empty-transcript path handles it (no new failure mode to wire up).
    """
    def _run(model: str) -> str:
        result = openai_client.audio.transcriptions.create(
            model=model,
            file=(filename, audio_bytes, content_type),
            prompt=STT_VOCABULARY,
        )
        return (result.text or "").strip()

    try:
        text = _run(VOICE_STT_MODEL)
    except Exception as e:
        print(f"⚠️ {VOICE_STT_MODEL} unavailable ({type(e).__name__}: {e}); falling back to whisper-1")
        text = _run("whisper-1")

    if _is_prompt_echo_or_noise(text):
        print(f"🔇 discarded non-speech transcript: {text[:80]!r}")
        return ""

    return text


def _synthesize_speech(text: str) -> bytes:
    """TTS with a graceful downgrade. The instruction-steerable model is the
    whole point (it's what makes the delivery stop being monotone), but if the
    account or SDK version doesn't support it, a flat reply is still far better
    than a failed turn."""
    try:
        speech = openai_client.audio.speech.create(
            model=VOICE_TTS_MODEL,
            voice=VOICE_TTS_VOICE,
            input=text,
            instructions=VOICE_TTS_INSTRUCTIONS,
        )
        return speech.read()
    except Exception as e:
        print(f"⚠️ {VOICE_TTS_MODEL} unavailable ({type(e).__name__}: {e}); falling back to {VOICE_TTS_FALLBACK_MODEL}")
        speech = openai_client.audio.speech.create(
            model=VOICE_TTS_FALLBACK_MODEL,
            voice=VOICE_TTS_VOICE,
            input=text,
        )
        return speech.read()


# Same assistant as /chat, just with a spoken front-end: an uploaded audio
# clip is transcribed (Whisper), run through the exact same session/history/
# tool-calling logic as text chat, then the reply is synthesized back to
# speech (OpenAI TTS). Session IDs are shared with /chat and /chat/stream —
# a conversation can move between typing and talking without losing context.
@app.post("/api/voice/chat")
async def voice_chat(audio: UploadFile = File(...), session_id: Optional[str] = None):
    if not OPENAI_API_KEY:
        raise HTTPException(status_code=500, detail="OPENAI_API_KEY is not set on the server")

    # Every stage here blocks on the one before it, so the turn's latency is
    # the sum of all of them. Timing each stage separately is the only way to
    # know which one to actually attack — the timings ride back in the
    # response so the browser console shows them too, not just server logs.
    t0 = time.perf_counter()
    timings: Dict[str, int] = {}

    def mark(stage: str, since: float) -> float:
        now = time.perf_counter()
        timings[stage] = int((now - since) * 1000)
        return now

    try:
        # Checked against the session BEFORE the clip is even read, let alone
        # transcribed — a capped session triggers zero OpenAI calls (no STT,
        # no LLM, no TTS), which is the entire point of checking this early.
        sid = get_or_create_session(session_id)
        history = sessions[sid]
        if session_limit_reached(history):
            return {
                "session_id": sid,
                "transcript": "",
                "response": SESSION_LIMIT_MESSAGE,
                "audio_base64": None,
                "audio_mime": None,
                "timings": {},
            }

        audio_bytes = await audio.read()
        if not audio_bytes:
            raise HTTPException(status_code=400, detail="Empty audio upload")
        t = mark("upload_read", t0)

        # Whisper needs a filename with a real extension to infer format —
        # browsers usually send webm/ogg from MediaRecorder.
        filename = audio.filename or "clip.webm"
        user_text = _transcribe(filename, audio_bytes, audio.content_type or "audio/webm")
        t = mark("stt", t)
        if not user_text:
            # Same non-event as in the streaming endpoint: nothing intelligible
            # in the clip. Return a benign empty turn rather than a 400 so the
            # client can just go back to listening, and append nothing to
            # history.
            return {
                "session_id": sid,
                "transcript": "",
                "response": "",
                "audio_base64": None,
                "audio_mime": None,
                "no_speech": True,
                "timings": timings,
            }

        # Identical path to /chat from here on — same session store, same
        # build_messages/run_chat_completion, same tool-calling loop.
        history.append(HumanMessage(content=user_text))

        # voice=True swaps in the spoken-delivery style overlay, and the
        # tighter token ceiling is a hard backstop in case the model ignores it.
        messages = build_messages(history, voice=True)
        reply_text = run_chat_completion(messages, max_tokens=220)
        t = mark("llm", t)

        history.append(AIMessage(content=reply_text))
        sessions[sid] = history

        audio_reply_bytes = _synthesize_speech(_shape_for_speech(reply_text))
        t = mark("tts", t)

        audio_b64 = base64.b64encode(audio_reply_bytes).decode("ascii")
        mark("encode", t)
        timings["total"] = int((time.perf_counter() - t0) * 1000)

        print(
            "🎙️ voice turn "
            + "  ".join(f"{k}={v}ms" for k, v in timings.items())
            + f"  audio={len(audio_reply_bytes) // 1024}KB"
        )

        return {
            "session_id": sid,
            "transcript": user_text,
            "response": reply_text,
            "audio_base64": audio_b64,
            "audio_mime": "audio/mpeg",
            "timings": timings,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"{type(e).__name__}: {e}")


# ---- streaming voice turn ----------------------------------------------
# The non-streaming endpoint above is strictly sequential: you don't hear the
# first word until the last word has been generated, synthesized and
# transferred. This one pipelines instead — the LLM is streamed, and the
# moment a complete sentence exists it goes straight to TTS and out to the
# browser while the rest of the reply is still being written. The client plays
# chunks from a queue, so the perceived wait becomes roughly "first sentence"
# instead of "whole turn".
#
# Later sentences are synthesized while the browser is busy playing the
# earlier ones, so their TTS time is hidden entirely.

# The first chunk is flushed as small as possible (latency is all that matters
# there). Later chunks are grouped up to this size, because a TTS call has
# fixed overhead and lots of tiny calls would stutter the delivery.
VOICE_CHUNK_MIN_CHARS = 60


def _pop_sentences(buffer: str):
    """Pull every complete sentence off the front of a growing buffer.

    The `(?=\\s|$)` lookahead is what stops "92.68" or "e.g." from being
    treated as a sentence end — a real terminator is followed by whitespace,
    a decimal point is followed by a digit."""
    import re

    out = []
    while True:
        m = re.search(r"[.!?](?=\s|$)", buffer)
        if not m:
            break
        idx = m.end()
        sentence = buffer[:idx].strip()
        buffer = buffer[idx:].lstrip()
        if sentence:
            out.append(sentence)
    return out, buffer


@app.post("/api/voice/chat/stream")
async def voice_chat_stream(audio: UploadFile = File(...), session_id: Optional[str] = None):
    t0 = time.perf_counter()

    setup_error = None
    user_text = ""
    sid = None
    messages = None
    history = None
    stt_ms = 0
    limit_hit = False
    no_speech = False

    # Session lookup and the limit check happen before anything else,
    # including reading the uploaded clip — a capped session is turned away
    # before it can trigger a single OpenAI call (no STT, no LLM, no TTS).
    # Transcription itself genuinely can't be pipelined with the rest —
    # there's nothing to say until we know what was asked — so once past
    # the cap check it happens up front, before the response starts
    # streaming.
    try:
        if not OPENAI_API_KEY:
            raise RuntimeError("OPENAI_API_KEY is not set on the server")

        sid = get_or_create_session(session_id)
        history = sessions[sid]
        if session_limit_reached(history):
            limit_hit = True
        else:
            audio_bytes = await audio.read()
            if not audio_bytes:
                raise RuntimeError("Empty audio upload")
            filename = audio.filename or "clip.webm"
            user_text = _transcribe(filename, audio_bytes, audio.content_type or "audio/webm")
            stt_ms = int((time.perf_counter() - t0) * 1000)
            if not user_text:
                # Not an error — the VAD just sent a clip with nothing
                # intelligible in it (silence, a cough, background noise, or a
                # transcript we discarded as prompt echo). Signalling this
                # distinctly lets the client drop straight back to listening
                # instead of showing a scary failure for a non-event. Nothing
                # is appended to history, so it doesn't burn a capped message
                # or pollute the conversation.
                no_speech = True
            else:
                history.append(HumanMessage(content=user_text))
                messages = build_messages(history, voice=True)
    except Exception as e:
        setup_error = f"{e}"
        print(f"❌ voice_chat_stream setup failed: {type(e).__name__}: {e}")

    def generate():
        if setup_error:
            yield f"data: {json.dumps({'type': 'error', 'error': setup_error})}\n\n"
            return

        if limit_hit:
            yield f"data: {json.dumps({'type': 'session', 'session_id': sid})}\n\n"
            yield f"data: {json.dumps({'type': 'text', 'content': SESSION_LIMIT_MESSAGE})}\n\n"
            yield f"data: {json.dumps({'type': 'done', 'response': SESSION_LIMIT_MESSAGE, 'stt_ms': 0, 'first_audio_ms': None, 'total_ms': int((time.perf_counter() - t0) * 1000)})}\n\n"
            return

        if no_speech:
            yield f"data: {json.dumps({'type': 'session', 'session_id': sid})}\n\n"
            yield f"data: {json.dumps({'type': 'no_speech'})}\n\n"
            return

        yield f"data: {json.dumps({'type': 'session', 'session_id': sid})}\n\n"
        yield f"data: {json.dumps({'type': 'transcript', 'text': user_text, 'stt_ms': stt_ms})}\n\n"

        full_text = ""
        buffer = ""
        pending = ""
        chunk_index = 0
        first_audio_at = None

        def emit_chunk(text_chunk: str, index: int):
            """Synthesize one chunk and hand it to the browser."""
            spoken = _shape_for_speech(text_chunk)
            if not spoken:
                return None
            audio_bytes_out = _synthesize_speech(spoken)
            return {
                "type": "audio",
                "index": index,
                "audio_base64": base64.b64encode(audio_bytes_out).decode("ascii"),
                "mime": "audio/mpeg",
            }

        try:
            for event in stream_chat_completion(messages, max_tokens=220):
                if event["type"] != "content" or not event["content"]:
                    continue
                full_text += event["content"]
                buffer += event["content"]

                sentences, buffer = _pop_sentences(buffer)
                for sentence in sentences:
                    pending = f"{pending} {sentence}".strip() if pending else sentence
                    # First chunk goes out immediately — that's the whole
                    # point. After that, group so we're not making a TTS
                    # call per three-word sentence.
                    if chunk_index == 0 or len(pending) >= VOICE_CHUNK_MIN_CHARS:
                        # Text first so captions stay ahead of the audio.
                        yield f"data: {json.dumps({'type': 'text', 'content': pending})}\n\n"
                        payload = emit_chunk(pending, chunk_index)
                        if payload:
                            if first_audio_at is None:
                                first_audio_at = int((time.perf_counter() - t0) * 1000)
                                payload["first_audio_ms"] = first_audio_at
                            yield f"data: {json.dumps(payload)}\n\n"
                            chunk_index += 1
                        pending = ""

            # Whatever's left when the model stops: the trailing partial
            # sentence plus any grouped text that never hit the size floor.
            tail = f"{pending} {buffer}".strip()
            if tail:
                yield f"data: {json.dumps({'type': 'text', 'content': tail})}\n\n"
                payload = emit_chunk(tail, chunk_index)
                if payload:
                    if first_audio_at is None:
                        first_audio_at = int((time.perf_counter() - t0) * 1000)
                        payload["first_audio_ms"] = first_audio_at
                    yield f"data: {json.dumps(payload)}\n\n"

            history.append(AIMessage(content=full_text))
            sessions[sid] = history

            total_ms = int((time.perf_counter() - t0) * 1000)
            print(f"🎙️ voice stream stt={stt_ms}ms first_audio={first_audio_at}ms total={total_ms}ms")
            yield f"data: {json.dumps({'type': 'done', 'response': full_text, 'stt_ms': stt_ms, 'first_audio_ms': first_audio_at, 'total_ms': total_ms})}\n\n"

        except Exception as e:
            import traceback
            traceback.print_exc()
            err = f"{type(e).__name__}: {e}"
            print(f"❌ voice_chat_stream generation failed: {err}")
            yield f"data: {json.dumps({'type': 'error', 'error': err})}\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive", "X-Accel-Buffering": "no"},
    )


# ================= PROJECTS ENDPOINT =================
@app.get("/api/projects")
async def get_projects(refresh: bool = False):
    """
    Returns all GitHub projects enriched by LLM.
    Results are cached for 1 hour. Pass ?refresh=true to force a rebuild.
    """
    global _projects_cache
    now = time.time()

    # Always serve from cache when available (in-memory or disk-loaded).
    # Refresh is now an explicit user action via /api/projects/refresh.
    if not refresh and _projects_cache.get("data"):
        return {
            "projects": _projects_cache["data"],
            "cached": True,
            "fetched_at": _projects_cache.get("fetched_at", now),
            "total": len(_projects_cache["data"]),
        }

    # Build fresh (incremental — only LLM-enrich new/changed repos)
    loop = asyncio.get_event_loop()
    existing = _projects_cache.get("data") if isinstance(_projects_cache, dict) else None
    projects = await loop.run_in_executor(None, _build_projects_list, existing)

    _projects_cache = {"data": projects, "fetched_at": now}
    _save_projects_to_disk(_projects_cache)
    return {
        "projects": projects,
        "cached": False,
        "fetched_at": now,
        "total": len(projects),
    }


@app.post("/api/projects/refresh")
async def refresh_projects():
    """
    Manual sync. Pulls the latest repo list from GitHub and incrementally
    enriches only new/changed repos with the LLM. Persists result to disk.
    Existing repos that haven't changed are reused (no LLM call).
    """
    global _projects_cache
    loop = asyncio.get_event_loop()
    existing = _projects_cache.get("data") if isinstance(_projects_cache, dict) else None
    projects = await loop.run_in_executor(None, _build_projects_list, existing)
    _projects_cache = {"data": projects, "fetched_at": time.time()}
    _save_projects_to_disk(_projects_cache)
    return {
        "message": "Projects synced",
        "total": len(projects),
        "fetched_at": _projects_cache["fetched_at"],
    }


# Serve React frontend static files
frontend_dist = Path("frontend/dist")
if frontend_dist.exists():
    app.mount("/assets", CachedStaticFiles(directory=frontend_dist / "assets"), name="assets")
    
    @app.get("/{full_path:path}")
    async def serve_frontend(full_path: str):
        # Serve index.html for all unknown routes (SPA fallback)
        # Check if the requested file exists in dist
        path = frontend_dist / full_path
        if path.is_file():
            return FileResponse(
                path,
                headers={"Cache-Control": "public, max-age=86400"},
            )
        return FileResponse(
            frontend_dist / "index.html",
            headers={"Cache-Control": "no-cache"},
        )
else:
    print("⚠️ Frontend dist directory not found. Please run 'npm run build' in the frontend folder.")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
